services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - WAHA_URL=http://waha:3000/api
    depends_on:
      - waha

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - BACKEND_URL=http://server:8000
  waha:
    image: devlikeapro/waha
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - ./.sessions:/app/.sessions
